/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int x_dot(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int x_dot_alloc_mem(void);
int x_dot_init_mem(int mem);
void x_dot_free_mem(int mem);
int x_dot_checkout(void);
void x_dot_release(int mem);
void x_dot_incref(void);
void x_dot_decref(void);
casadi_int x_dot_n_out(void);
casadi_int x_dot_n_in(void);
casadi_real x_dot_default_in(casadi_int i);
const char* x_dot_name_in(casadi_int i);
const char* x_dot_name_out(casadi_int i);
const casadi_int* x_dot_sparsity_in(casadi_int i);
const casadi_int* x_dot_sparsity_out(casadi_int i);
int x_dot_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int phi_x(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int phi_x_alloc_mem(void);
int phi_x_init_mem(int mem);
void phi_x_free_mem(int mem);
int phi_x_checkout(void);
void phi_x_release(int mem);
void phi_x_incref(void);
void phi_x_decref(void);
casadi_int phi_x_n_out(void);
casadi_int phi_x_n_in(void);
casadi_real phi_x_default_in(casadi_int i);
const char* phi_x_name_in(casadi_int i);
const char* phi_x_name_out(casadi_int i);
const casadi_int* phi_x_sparsity_in(casadi_int i);
const casadi_int* phi_x_sparsity_out(casadi_int i);
int phi_x_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int phi_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int phi_u_alloc_mem(void);
int phi_u_init_mem(int mem);
void phi_u_free_mem(int mem);
int phi_u_checkout(void);
void phi_u_release(int mem);
void phi_u_incref(void);
void phi_u_decref(void);
casadi_int phi_u_n_out(void);
casadi_int phi_u_n_in(void);
casadi_real phi_u_default_in(casadi_int i);
const char* phi_u_name_in(casadi_int i);
const char* phi_u_name_out(casadi_int i);
const casadi_int* phi_u_sparsity_in(casadi_int i);
const casadi_int* phi_u_sparsity_out(casadi_int i);
int phi_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int obj_ms(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int obj_ms_alloc_mem(void);
int obj_ms_init_mem(int mem);
void obj_ms_free_mem(int mem);
int obj_ms_checkout(void);
void obj_ms_release(int mem);
void obj_ms_incref(void);
void obj_ms_decref(void);
casadi_int obj_ms_n_out(void);
casadi_int obj_ms_n_in(void);
casadi_real obj_ms_default_in(casadi_int i);
const char* obj_ms_name_in(casadi_int i);
const char* obj_ms_name_out(casadi_int i);
const casadi_int* obj_ms_sparsity_in(casadi_int i);
const casadi_int* obj_ms_sparsity_out(casadi_int i);
int obj_ms_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int eql_ms(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int eql_ms_alloc_mem(void);
int eql_ms_init_mem(int mem);
void eql_ms_free_mem(int mem);
int eql_ms_checkout(void);
void eql_ms_release(int mem);
void eql_ms_incref(void);
void eql_ms_decref(void);
casadi_int eql_ms_n_out(void);
casadi_int eql_ms_n_in(void);
casadi_real eql_ms_default_in(casadi_int i);
const char* eql_ms_name_in(casadi_int i);
const char* eql_ms_name_out(casadi_int i);
const casadi_int* eql_ms_sparsity_in(casadi_int i);
const casadi_int* eql_ms_sparsity_out(casadi_int i);
int eql_ms_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
