/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) gen_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s3[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s4[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};

/* x_dot:(i0[4],i1,i2[11])->(o0[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[2]? arg[2][5] : 0;
  a2=arg[2]? arg[2][6] : 0;
  a3=arg[0]? arg[0][0] : 0;
  a4=(a2-a3);
  a4=sin(a4);
  a4=(a1*a4);
  a5=(a4*a0);
  a6=3.4877232142857140e-003;
  a7=2.8672000000000003e+002;
  a8=arg[2]? arg[2][9] : 0;
  a9=arg[2]? arg[2][10] : 0;
  a10=arg[2]? arg[2][8] : 0;
  a11=(a3-a10);
  a12=3.1415926535897931e+000;
  a11=(a11-a12);
  a11=cos(a11);
  a9=(a9*a11);
  a8=(a8+a9);
  a8=(a7*a8);
  a9=-5.3215770038167946e+001;
  a11=arg[0]? arg[0][1] : 0;
  a12=2.2204460492503131e-016;
  a11=(a11+a12);
  a2=(a2-a3);
  a2=cos(a2);
  a1=(a1*a2);
  a2=(a11-a1);
  a12=casadi_sq(a2);
  a13=arg[0]? arg[0][2] : 0;
  a4=(a13-a4);
  a14=casadi_sq(a4);
  a12=(a12+a14);
  a9=(a9*a12);
  a14=arg[1]? arg[1][0] : 0;
  a15=(a4/a2);
  a15=atan(a15);
  a15=(a14-a15);
  a15=sin(a15);
  a9=(a9*a15);
  a16=sin(a14);
  a9=(a9*a16);
  a8=(a8+a9);
  a9=-5.0399999999999993e-002;
  a16=arg[2]? arg[2][7] : 0;
  a17=(a10-a3);
  a17=cos(a17);
  a17=(a16*a17);
  a11=(a11-a17);
  a17=casadi_sq(a11);
  a10=(a10-a3);
  a10=sin(a10);
  a16=(a16*a10);
  a13=(a13-a16);
  a16=casadi_sq(a13);
  a17=(a17+a16);
  a9=(a9*a17);
  a13=atan2(a13,a11);
  a11=(-a13);
  a16=cos(a11);
  a9=(a9*a16);
  a8=(a8+a9);
  a7=(a7*a2);
  a9=-280.;
  a9=(a9*a0);
  a9=(a9*a4);
  a7=(a7+a9);
  a8=(a8-a7);
  a6=(a6*a8);
  a5=(a5+a6);
  if (res[0]!=0) res[0][1]=a5;
  a5=2.6042137004330460e-003;
  a6=-1.0072385496183207e+002;
  a6=(a6*a12);
  a6=(a6*a15);
  a8=cos(a14);
  a6=(a6*a8);
  a8=5.0400000000000000e-001;
  a8=(a8*a17);
  a11=sin(a11);
  a8=(a8*a11);
  a6=(a6+a8);
  a8=280.;
  a8=(a8*a0);
  a8=(a8*a2);
  a2=1.9455500000000001e+002;
  a2=(a2*a4);
  a8=(a8+a2);
  a6=(a6-a8);
  a5=(a5*a6);
  a8=-1.7772670617384389e-004;
  a2=2.0774295085877864e+002;
  a2=(a2*a12);
  a2=(a2*a15);
  a14=cos(a14);
  a2=(a2*a14);
  a14=1.7999999999999999e-001;
  a14=(a14*a17);
  a17=2.;
  a17=(a17*a13);
  a17=(-a17);
  a17=sin(a17);
  a14=(a14*a17);
  a2=(a2+a14);
  a14=1.0986460000000000e+003;
  a14=(a14*a0);
  a2=(a2-a14);
  a14=(a8*a2);
  a5=(a5+a14);
  a1=(a1*a0);
  a5=(a5-a1);
  if (res[0]!=0) res[0][2]=a5;
  a8=(a8*a6);
  a6=9.2234040170855987e-004;
  a6=(a6*a2);
  a8=(a8+a6);
  if (res[0]!=0) res[0][3]=a8;
  return 0;
}

CASADI_SYMBOL_EXPORT int x_dot(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int x_dot_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int x_dot_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void x_dot_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int x_dot_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void x_dot_release(int mem) {
}

CASADI_SYMBOL_EXPORT void x_dot_incref(void) {
}

CASADI_SYMBOL_EXPORT void x_dot_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int x_dot_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int x_dot_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real x_dot_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* x_dot_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* x_dot_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x_dot_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* x_dot_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int x_dot_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* phi_x:(i0[4],i1[11])->(o0) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=4.5000000000000000e+000;
  a1=arg[1]? arg[1][4] : 0;
  a2=arg[0]? arg[0][0] : 0;
  a1=(a1-a2);
  a2=arg[0]? arg[0][2] : 0;
  a3=arg[0]? arg[0][1] : 0;
  a4=2.2204460492503131e-016;
  a3=(a3+a4);
  a2=(a2/a3);
  a2=atan(a2);
  a1=(a1-a2);
  a0=(a0*a1);
  a0=(a0*a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int phi_x(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int phi_x_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int phi_x_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void phi_x_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int phi_x_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void phi_x_release(int mem) {
}

CASADI_SYMBOL_EXPORT void phi_x_incref(void) {
}

CASADI_SYMBOL_EXPORT void phi_x_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int phi_x_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int phi_x_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real phi_x_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* phi_x_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* phi_x_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* phi_x_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* phi_x_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int phi_x_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* phi_u:(i0)->(o0) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=5.0000000000000003e-002;
  a1=arg[0]? arg[0][0] : 0;
  a0=(a0*a1);
  a0=(a0*a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int phi_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int phi_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int phi_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void phi_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int phi_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void phi_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void phi_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void phi_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int phi_u_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int phi_u_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real phi_u_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* phi_u_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* phi_u_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* phi_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* phi_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int phi_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* obj_ms:(i0[14],i1[11])->(o0) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=4.5000000000000000e+000;
  a1=arg[1]? arg[1][4] : 0;
  a2=arg[0]? arg[0][0] : 0;
  a2=(a1-a2);
  a3=arg[0]? arg[0][2] : 0;
  a4=arg[0]? arg[0][1] : 0;
  a5=2.2204460492503131e-016;
  a4=(a4+a5);
  a3=(a3/a4);
  a3=atan(a3);
  a2=(a2-a3);
  a3=(a0*a2);
  a3=(a3*a2);
  a2=5.0000000000000003e-002;
  a4=arg[0]? arg[0][12] : 0;
  a6=(a2*a4);
  a6=(a6*a4);
  a3=(a3+a6);
  a6=arg[0]? arg[0][4] : 0;
  a1=(a1-a6);
  a6=arg[0]? arg[0][6] : 0;
  a7=arg[0]? arg[0][5] : 0;
  a7=(a7+a5);
  a6=(a6/a7);
  a6=atan(a6);
  a1=(a1-a6);
  a0=(a0*a1);
  a0=(a0*a1);
  a3=(a3+a0);
  a0=arg[0]? arg[0][13] : 0;
  a4=(a4-a0);
  a2=(a2*a4);
  a2=(a2*a4);
  a3=(a3+a2);
  if (res[0]!=0) res[0][0]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_ms(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int obj_ms_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int obj_ms_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_ms_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int obj_ms_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obj_ms_release(int mem) {
}

CASADI_SYMBOL_EXPORT void obj_ms_incref(void) {
}

CASADI_SYMBOL_EXPORT void obj_ms_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int obj_ms_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int obj_ms_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real obj_ms_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_ms_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obj_ms_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_ms_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obj_ms_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obj_ms_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* eql_ms:(i0[14],i1[11])->(o0[12]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[1]? arg[1][0] : 0;
  a1=(a0-a1);
  a2=3.1415926535897931e+000;
  a1=(a1+a2);
  a3=6.2831853071795862e+000;
  a1=fmod(a1,a3);
  a1=(a1-a2);
  if (res[0]!=0) res[0][0]=a1;
  a1=arg[0]? arg[0][1] : 0;
  a4=arg[1]? arg[1][1] : 0;
  a4=(a1-a4);
  if (res[0]!=0) res[0][1]=a4;
  a4=arg[0]? arg[0][2] : 0;
  a5=arg[1]? arg[1][2] : 0;
  a5=(a4-a5);
  if (res[0]!=0) res[0][2]=a5;
  a5=arg[0]? arg[0][3] : 0;
  a6=arg[1]? arg[1][3] : 0;
  a6=(a5-a6);
  if (res[0]!=0) res[0][3]=a6;
  a6=arg[0]? arg[0][4] : 0;
  a7=8.3333333333333329e-002;
  a8=2.;
  a9=2.5000000000000000e-001;
  a10=-1.7772670617384389e-004;
  a11=-1.0072385496183207e+002;
  a12=2.2204460492503131e-016;
  a13=(a1+a12);
  a14=arg[1]? arg[1][5] : 0;
  a15=arg[1]? arg[1][6] : 0;
  a16=(a15-a0);
  a16=cos(a16);
  a16=(a14*a16);
  a17=(a13-a16);
  a18=casadi_sq(a17);
  a19=(a15-a0);
  a19=sin(a19);
  a19=(a14*a19);
  a20=(a4-a19);
  a21=casadi_sq(a20);
  a18=(a18+a21);
  a21=(a11*a18);
  a22=arg[0]? arg[0][12] : 0;
  a23=(a20/a17);
  a23=atan(a23);
  a23=(a22-a23);
  a23=sin(a23);
  a21=(a21*a23);
  a24=cos(a22);
  a21=(a21*a24);
  a24=5.0400000000000000e-001;
  a25=arg[1]? arg[1][7] : 0;
  a26=arg[1]? arg[1][8] : 0;
  a27=(a26-a0);
  a27=cos(a27);
  a27=(a25*a27);
  a13=(a13-a27);
  a27=casadi_sq(a13);
  a28=(a26-a0);
  a28=sin(a28);
  a28=(a25*a28);
  a28=(a4-a28);
  a29=casadi_sq(a28);
  a27=(a27+a29);
  a29=(a24*a27);
  a28=atan2(a28,a13);
  a13=(-a28);
  a30=sin(a13);
  a29=(a29*a30);
  a21=(a21+a29);
  a29=280.;
  a30=(a29*a5);
  a30=(a30*a17);
  a31=1.9455500000000001e+002;
  a32=(a31*a20);
  a30=(a30+a32);
  a21=(a21-a30);
  a30=(a10*a21);
  a32=9.2234040170855987e-004;
  a33=2.0774295085877864e+002;
  a34=(a33*a18);
  a34=(a34*a23);
  a35=cos(a22);
  a34=(a34*a35);
  a35=1.7999999999999999e-001;
  a36=(a35*a27);
  a28=(a8*a28);
  a28=(-a28);
  a28=sin(a28);
  a36=(a36*a28);
  a34=(a34+a36);
  a36=1.0986460000000000e+003;
  a28=(a36*a5);
  a34=(a34-a28);
  a28=(a32*a34);
  a30=(a30+a28);
  a28=(a9*a30);
  a28=(a5+a28);
  a37=(a8*a28);
  a37=(a5+a37);
  a19=(a19*a5);
  a38=3.4877232142857140e-003;
  a39=2.8672000000000003e+002;
  a40=arg[1]? arg[1][9] : 0;
  a41=arg[1]? arg[1][10] : 0;
  a42=(a0-a26);
  a42=(a42-a2);
  a42=cos(a42);
  a42=(a41*a42);
  a42=(a40+a42);
  a42=(a39*a42);
  a43=-5.3215770038167946e+001;
  a18=(a43*a18);
  a18=(a18*a23);
  a23=sin(a22);
  a18=(a18*a23);
  a42=(a42+a18);
  a18=-5.0399999999999993e-002;
  a27=(a18*a27);
  a13=cos(a13);
  a27=(a27*a13);
  a42=(a42+a27);
  a17=(a39*a17);
  a27=-280.;
  a13=(a27*a5);
  a13=(a13*a20);
  a17=(a17+a13);
  a42=(a42-a17);
  a42=(a38*a42);
  a19=(a19+a42);
  a42=(a9*a19);
  a42=(a1+a42);
  a42=(a42+a12);
  a17=(a9*a5);
  a17=(a0+a17);
  a13=(a15-a17);
  a13=cos(a13);
  a13=(a14*a13);
  a20=(a42-a13);
  a23=casadi_sq(a20);
  a44=2.6042137004330460e-003;
  a21=(a44*a21);
  a34=(a10*a34);
  a21=(a21+a34);
  a16=(a16*a5);
  a21=(a21-a16);
  a16=(a9*a21);
  a16=(a4+a16);
  a34=(a15-a17);
  a34=sin(a34);
  a34=(a14*a34);
  a45=(a16-a34);
  a46=casadi_sq(a45);
  a23=(a23+a46);
  a46=(a11*a23);
  a47=(a45/a20);
  a47=atan(a47);
  a47=(a22-a47);
  a47=sin(a47);
  a46=(a46*a47);
  a48=cos(a22);
  a46=(a46*a48);
  a48=(a26-a17);
  a48=cos(a48);
  a48=(a25*a48);
  a42=(a42-a48);
  a48=casadi_sq(a42);
  a49=(a26-a17);
  a49=sin(a49);
  a49=(a25*a49);
  a16=(a16-a49);
  a49=casadi_sq(a16);
  a48=(a48+a49);
  a49=(a24*a48);
  a16=atan2(a16,a42);
  a42=(-a16);
  a50=sin(a42);
  a49=(a49*a50);
  a46=(a46+a49);
  a49=(a29*a28);
  a49=(a49*a20);
  a50=(a31*a45);
  a49=(a49+a50);
  a46=(a46-a49);
  a49=(a10*a46);
  a50=(a33*a23);
  a50=(a50*a47);
  a51=cos(a22);
  a50=(a50*a51);
  a51=(a35*a48);
  a16=(a8*a16);
  a16=(-a16);
  a16=sin(a16);
  a51=(a51*a16);
  a50=(a50+a51);
  a51=(a36*a28);
  a50=(a50-a51);
  a51=(a32*a50);
  a49=(a49+a51);
  a51=(a9*a49);
  a51=(a5+a51);
  a16=(a8*a51);
  a37=(a37+a16);
  a16=5.0000000000000000e-001;
  a34=(a34*a28);
  a17=(a17-a26);
  a17=(a17-a2);
  a17=cos(a17);
  a17=(a41*a17);
  a17=(a40+a17);
  a17=(a39*a17);
  a23=(a43*a23);
  a23=(a23*a47);
  a47=sin(a22);
  a23=(a23*a47);
  a17=(a17+a23);
  a48=(a18*a48);
  a42=cos(a42);
  a48=(a48*a42);
  a17=(a17+a48);
  a20=(a39*a20);
  a48=(a27*a28);
  a48=(a48*a45);
  a20=(a20+a48);
  a17=(a17-a20);
  a17=(a38*a17);
  a34=(a34+a17);
  a17=(a9*a34);
  a17=(a1+a17);
  a17=(a17+a12);
  a20=(a9*a28);
  a20=(a0+a20);
  a48=(a15-a20);
  a48=cos(a48);
  a48=(a14*a48);
  a45=(a17-a48);
  a42=casadi_sq(a45);
  a46=(a44*a46);
  a50=(a10*a50);
  a46=(a46+a50);
  a13=(a13*a28);
  a46=(a46-a13);
  a13=(a9*a46);
  a13=(a4+a13);
  a28=(a15-a20);
  a28=sin(a28);
  a28=(a14*a28);
  a50=(a13-a28);
  a23=casadi_sq(a50);
  a42=(a42+a23);
  a23=(a11*a42);
  a47=(a50/a45);
  a47=atan(a47);
  a47=(a22-a47);
  a47=sin(a47);
  a23=(a23*a47);
  a52=cos(a22);
  a23=(a23*a52);
  a52=(a26-a20);
  a52=cos(a52);
  a52=(a25*a52);
  a17=(a17-a52);
  a52=casadi_sq(a17);
  a53=(a26-a20);
  a53=sin(a53);
  a53=(a25*a53);
  a13=(a13-a53);
  a53=casadi_sq(a13);
  a52=(a52+a53);
  a53=(a24*a52);
  a13=atan2(a13,a17);
  a17=(-a13);
  a54=sin(a17);
  a53=(a53*a54);
  a23=(a23+a53);
  a53=(a29*a51);
  a53=(a53*a45);
  a54=(a31*a50);
  a53=(a53+a54);
  a23=(a23-a53);
  a53=(a10*a23);
  a54=(a33*a42);
  a54=(a54*a47);
  a55=cos(a22);
  a54=(a54*a55);
  a55=(a35*a52);
  a13=(a8*a13);
  a13=(-a13);
  a13=sin(a13);
  a55=(a55*a13);
  a54=(a54+a55);
  a55=(a36*a51);
  a54=(a54-a55);
  a55=(a32*a54);
  a53=(a53+a55);
  a55=(a16*a53);
  a55=(a5+a55);
  a37=(a37+a55);
  a37=(a7*a37);
  a37=(a0+a37);
  a37=(a6-a37);
  a37=(a37+a2);
  a37=fmod(a37,a3);
  a37=(a37-a2);
  if (res[0]!=0) res[0][4]=a37;
  a37=arg[0]? arg[0][5] : 0;
  a34=(a8*a34);
  a19=(a19+a34);
  a28=(a28*a51);
  a20=(a20-a26);
  a20=(a20-a2);
  a20=cos(a20);
  a20=(a41*a20);
  a20=(a40+a20);
  a20=(a39*a20);
  a42=(a43*a42);
  a42=(a42*a47);
  a47=sin(a22);
  a42=(a42*a47);
  a20=(a20+a42);
  a52=(a18*a52);
  a17=cos(a17);
  a52=(a52*a17);
  a20=(a20+a52);
  a45=(a39*a45);
  a52=(a27*a51);
  a52=(a52*a50);
  a45=(a45+a52);
  a20=(a20-a45);
  a20=(a38*a20);
  a28=(a28+a20);
  a20=(a8*a28);
  a19=(a19+a20);
  a20=(a16*a51);
  a0=(a0+a20);
  a20=(a15-a0);
  a20=sin(a20);
  a20=(a14*a20);
  a45=(a20*a55);
  a52=(a0-a26);
  a52=(a52-a2);
  a52=cos(a52);
  a52=(a41*a52);
  a52=(a40+a52);
  a52=(a39*a52);
  a28=(a16*a28);
  a28=(a1+a28);
  a28=(a28+a12);
  a50=(a15-a0);
  a50=cos(a50);
  a50=(a14*a50);
  a17=(a28-a50);
  a42=casadi_sq(a17);
  a23=(a44*a23);
  a54=(a10*a54);
  a23=(a23+a54);
  a48=(a48*a51);
  a23=(a23-a48);
  a48=(a16*a23);
  a48=(a4+a48);
  a20=(a48-a20);
  a51=casadi_sq(a20);
  a42=(a42+a51);
  a51=(a43*a42);
  a54=(a20/a17);
  a54=atan(a54);
  a54=(a22-a54);
  a54=sin(a54);
  a51=(a51*a54);
  a47=sin(a22);
  a51=(a51*a47);
  a52=(a52+a51);
  a51=(a26-a0);
  a51=cos(a51);
  a51=(a25*a51);
  a28=(a28-a51);
  a51=casadi_sq(a28);
  a0=(a26-a0);
  a0=sin(a0);
  a0=(a25*a0);
  a48=(a48-a0);
  a0=casadi_sq(a48);
  a51=(a51+a0);
  a0=(a18*a51);
  a48=atan2(a48,a28);
  a28=(-a48);
  a47=cos(a28);
  a0=(a0*a47);
  a52=(a52+a0);
  a0=(a39*a17);
  a47=(a27*a55);
  a47=(a47*a20);
  a0=(a0+a47);
  a52=(a52-a0);
  a52=(a38*a52);
  a45=(a45+a52);
  a19=(a19+a45);
  a19=(a7*a19);
  a1=(a1+a19);
  a1=(a37-a1);
  if (res[0]!=0) res[0][5]=a1;
  a1=arg[0]? arg[0][6] : 0;
  a46=(a8*a46);
  a21=(a21+a46);
  a23=(a8*a23);
  a21=(a21+a23);
  a23=(a11*a42);
  a23=(a23*a54);
  a46=cos(a22);
  a23=(a23*a46);
  a46=(a24*a51);
  a28=sin(a28);
  a46=(a46*a28);
  a23=(a23+a46);
  a46=(a29*a55);
  a46=(a46*a17);
  a20=(a31*a20);
  a46=(a46+a20);
  a23=(a23-a46);
  a46=(a44*a23);
  a42=(a33*a42);
  a42=(a42*a54);
  a22=cos(a22);
  a42=(a42*a22);
  a51=(a35*a51);
  a48=(a8*a48);
  a48=(-a48);
  a48=sin(a48);
  a51=(a51*a48);
  a42=(a42+a51);
  a51=(a36*a55);
  a42=(a42-a51);
  a51=(a10*a42);
  a46=(a46+a51);
  a50=(a50*a55);
  a46=(a46-a50);
  a21=(a21+a46);
  a21=(a7*a21);
  a4=(a4+a21);
  a4=(a1-a4);
  if (res[0]!=0) res[0][6]=a4;
  a4=arg[0]? arg[0][7] : 0;
  a49=(a8*a49);
  a30=(a30+a49);
  a53=(a8*a53);
  a30=(a30+a53);
  a23=(a10*a23);
  a42=(a32*a42);
  a23=(a23+a42);
  a30=(a30+a23);
  a30=(a7*a30);
  a5=(a5+a30);
  a5=(a4-a5);
  if (res[0]!=0) res[0][7]=a5;
  a5=arg[0]? arg[0][8] : 0;
  a30=(a37+a12);
  a23=(a15-a6);
  a23=cos(a23);
  a23=(a14*a23);
  a42=(a30-a23);
  a53=casadi_sq(a42);
  a49=(a15-a6);
  a49=sin(a49);
  a49=(a14*a49);
  a21=(a1-a49);
  a46=casadi_sq(a21);
  a53=(a53+a46);
  a46=(a11*a53);
  a50=arg[0]? arg[0][13] : 0;
  a55=(a21/a42);
  a55=atan(a55);
  a55=(a50-a55);
  a55=sin(a55);
  a46=(a46*a55);
  a51=cos(a50);
  a46=(a46*a51);
  a51=(a26-a6);
  a51=cos(a51);
  a51=(a25*a51);
  a30=(a30-a51);
  a51=casadi_sq(a30);
  a48=(a26-a6);
  a48=sin(a48);
  a48=(a25*a48);
  a48=(a1-a48);
  a22=casadi_sq(a48);
  a51=(a51+a22);
  a22=(a24*a51);
  a48=atan2(a48,a30);
  a30=(-a48);
  a54=sin(a30);
  a22=(a22*a54);
  a46=(a46+a22);
  a22=(a29*a4);
  a22=(a22*a42);
  a54=(a31*a21);
  a22=(a22+a54);
  a46=(a46-a22);
  a22=(a10*a46);
  a54=(a33*a53);
  a54=(a54*a55);
  a20=cos(a50);
  a54=(a54*a20);
  a20=(a35*a51);
  a48=(a8*a48);
  a48=(-a48);
  a48=sin(a48);
  a20=(a20*a48);
  a54=(a54+a20);
  a20=(a36*a4);
  a54=(a54-a20);
  a20=(a32*a54);
  a22=(a22+a20);
  a20=(a9*a22);
  a20=(a4+a20);
  a48=(a8*a20);
  a48=(a4+a48);
  a49=(a49*a4);
  a17=(a6-a26);
  a17=(a17-a2);
  a17=cos(a17);
  a17=(a41*a17);
  a17=(a40+a17);
  a17=(a39*a17);
  a53=(a43*a53);
  a53=(a53*a55);
  a55=sin(a50);
  a53=(a53*a55);
  a17=(a17+a53);
  a51=(a18*a51);
  a30=cos(a30);
  a51=(a51*a30);
  a17=(a17+a51);
  a42=(a39*a42);
  a51=(a27*a4);
  a51=(a51*a21);
  a42=(a42+a51);
  a17=(a17-a42);
  a17=(a38*a17);
  a49=(a49+a17);
  a17=(a9*a49);
  a17=(a37+a17);
  a17=(a17+a12);
  a42=(a9*a4);
  a42=(a6+a42);
  a51=(a15-a42);
  a51=cos(a51);
  a51=(a14*a51);
  a21=(a17-a51);
  a30=casadi_sq(a21);
  a46=(a44*a46);
  a54=(a10*a54);
  a46=(a46+a54);
  a23=(a23*a4);
  a46=(a46-a23);
  a23=(a9*a46);
  a23=(a1+a23);
  a54=(a15-a42);
  a54=sin(a54);
  a54=(a14*a54);
  a53=(a23-a54);
  a55=casadi_sq(a53);
  a30=(a30+a55);
  a55=(a11*a30);
  a28=(a53/a21);
  a28=atan(a28);
  a28=(a50-a28);
  a28=sin(a28);
  a55=(a55*a28);
  a19=cos(a50);
  a55=(a55*a19);
  a19=(a26-a42);
  a19=cos(a19);
  a19=(a25*a19);
  a17=(a17-a19);
  a19=casadi_sq(a17);
  a45=(a26-a42);
  a45=sin(a45);
  a45=(a25*a45);
  a23=(a23-a45);
  a45=casadi_sq(a23);
  a19=(a19+a45);
  a45=(a24*a19);
  a23=atan2(a23,a17);
  a17=(-a23);
  a52=sin(a17);
  a45=(a45*a52);
  a55=(a55+a45);
  a45=(a29*a20);
  a45=(a45*a21);
  a52=(a31*a53);
  a45=(a45+a52);
  a55=(a55-a45);
  a45=(a10*a55);
  a52=(a33*a30);
  a52=(a52*a28);
  a0=cos(a50);
  a52=(a52*a0);
  a0=(a35*a19);
  a23=(a8*a23);
  a23=(-a23);
  a23=sin(a23);
  a0=(a0*a23);
  a52=(a52+a0);
  a0=(a36*a20);
  a52=(a52-a0);
  a0=(a32*a52);
  a45=(a45+a0);
  a0=(a9*a45);
  a0=(a4+a0);
  a23=(a8*a0);
  a48=(a48+a23);
  a54=(a54*a20);
  a42=(a42-a26);
  a42=(a42-a2);
  a42=cos(a42);
  a42=(a41*a42);
  a42=(a40+a42);
  a42=(a39*a42);
  a30=(a43*a30);
  a30=(a30*a28);
  a28=sin(a50);
  a30=(a30*a28);
  a42=(a42+a30);
  a19=(a18*a19);
  a17=cos(a17);
  a19=(a19*a17);
  a42=(a42+a19);
  a21=(a39*a21);
  a19=(a27*a20);
  a19=(a19*a53);
  a21=(a21+a19);
  a42=(a42-a21);
  a42=(a38*a42);
  a54=(a54+a42);
  a42=(a9*a54);
  a42=(a37+a42);
  a42=(a42+a12);
  a21=(a9*a20);
  a21=(a6+a21);
  a19=(a15-a21);
  a19=cos(a19);
  a19=(a14*a19);
  a53=(a42-a19);
  a17=casadi_sq(a53);
  a55=(a44*a55);
  a52=(a10*a52);
  a55=(a55+a52);
  a51=(a51*a20);
  a55=(a55-a51);
  a9=(a9*a55);
  a9=(a1+a9);
  a51=(a15-a21);
  a51=sin(a51);
  a51=(a14*a51);
  a20=(a9-a51);
  a52=casadi_sq(a20);
  a17=(a17+a52);
  a52=(a11*a17);
  a30=(a20/a53);
  a30=atan(a30);
  a30=(a50-a30);
  a30=sin(a30);
  a52=(a52*a30);
  a28=cos(a50);
  a52=(a52*a28);
  a28=(a26-a21);
  a28=cos(a28);
  a28=(a25*a28);
  a42=(a42-a28);
  a28=casadi_sq(a42);
  a23=(a26-a21);
  a23=sin(a23);
  a23=(a25*a23);
  a9=(a9-a23);
  a23=casadi_sq(a9);
  a28=(a28+a23);
  a23=(a24*a28);
  a9=atan2(a9,a42);
  a42=(-a9);
  a47=sin(a42);
  a23=(a23*a47);
  a52=(a52+a23);
  a23=(a29*a0);
  a23=(a23*a53);
  a47=(a31*a20);
  a23=(a23+a47);
  a52=(a52-a23);
  a23=(a10*a52);
  a47=(a33*a17);
  a47=(a47*a30);
  a34=cos(a50);
  a47=(a47*a34);
  a34=(a35*a28);
  a9=(a8*a9);
  a9=(-a9);
  a9=sin(a9);
  a34=(a34*a9);
  a47=(a47+a34);
  a34=(a36*a0);
  a47=(a47-a34);
  a34=(a32*a47);
  a23=(a23+a34);
  a34=(a16*a23);
  a34=(a4+a34);
  a48=(a48+a34);
  a48=(a7*a48);
  a48=(a6+a48);
  a5=(a5-a48);
  a5=(a5+a2);
  a5=fmod(a5,a3);
  a5=(a5-a2);
  if (res[0]!=0) res[0][8]=a5;
  a5=arg[0]? arg[0][9] : 0;
  a54=(a8*a54);
  a49=(a49+a54);
  a51=(a51*a0);
  a21=(a21-a26);
  a21=(a21-a2);
  a21=cos(a21);
  a21=(a41*a21);
  a21=(a40+a21);
  a21=(a39*a21);
  a17=(a43*a17);
  a17=(a17*a30);
  a30=sin(a50);
  a17=(a17*a30);
  a21=(a21+a17);
  a28=(a18*a28);
  a42=cos(a42);
  a28=(a28*a42);
  a21=(a21+a28);
  a53=(a39*a53);
  a28=(a27*a0);
  a28=(a28*a20);
  a53=(a53+a28);
  a21=(a21-a53);
  a21=(a38*a21);
  a51=(a51+a21);
  a21=(a8*a51);
  a49=(a49+a21);
  a21=(a16*a0);
  a6=(a6+a21);
  a21=(a15-a6);
  a21=sin(a21);
  a21=(a14*a21);
  a53=(a21*a34);
  a28=(a6-a26);
  a28=(a28-a2);
  a28=cos(a28);
  a41=(a41*a28);
  a40=(a40+a41);
  a40=(a39*a40);
  a51=(a16*a51);
  a51=(a37+a51);
  a51=(a51+a12);
  a15=(a15-a6);
  a15=cos(a15);
  a14=(a14*a15);
  a15=(a51-a14);
  a12=casadi_sq(a15);
  a52=(a44*a52);
  a47=(a10*a47);
  a52=(a52+a47);
  a19=(a19*a0);
  a52=(a52-a19);
  a16=(a16*a52);
  a16=(a1+a16);
  a21=(a16-a21);
  a19=casadi_sq(a21);
  a12=(a12+a19);
  a43=(a43*a12);
  a19=(a21/a15);
  a19=atan(a19);
  a19=(a50-a19);
  a19=sin(a19);
  a43=(a43*a19);
  a0=sin(a50);
  a43=(a43*a0);
  a40=(a40+a43);
  a43=(a26-a6);
  a43=cos(a43);
  a43=(a25*a43);
  a51=(a51-a43);
  a43=casadi_sq(a51);
  a26=(a26-a6);
  a26=sin(a26);
  a25=(a25*a26);
  a16=(a16-a25);
  a25=casadi_sq(a16);
  a43=(a43+a25);
  a18=(a18*a43);
  a16=atan2(a16,a51);
  a51=(-a16);
  a25=cos(a51);
  a18=(a18*a25);
  a40=(a40+a18);
  a39=(a39*a15);
  a27=(a27*a34);
  a27=(a27*a21);
  a39=(a39+a27);
  a40=(a40-a39);
  a38=(a38*a40);
  a53=(a53+a38);
  a49=(a49+a53);
  a49=(a7*a49);
  a37=(a37+a49);
  a5=(a5-a37);
  if (res[0]!=0) res[0][9]=a5;
  a5=arg[0]? arg[0][10] : 0;
  a55=(a8*a55);
  a46=(a46+a55);
  a52=(a8*a52);
  a46=(a46+a52);
  a11=(a11*a12);
  a11=(a11*a19);
  a52=cos(a50);
  a11=(a11*a52);
  a24=(a24*a43);
  a51=sin(a51);
  a24=(a24*a51);
  a11=(a11+a24);
  a29=(a29*a34);
  a29=(a29*a15);
  a31=(a31*a21);
  a29=(a29+a31);
  a11=(a11-a29);
  a44=(a44*a11);
  a33=(a33*a12);
  a33=(a33*a19);
  a50=cos(a50);
  a33=(a33*a50);
  a35=(a35*a43);
  a16=(a8*a16);
  a16=(-a16);
  a16=sin(a16);
  a35=(a35*a16);
  a33=(a33+a35);
  a36=(a36*a34);
  a33=(a33-a36);
  a36=(a10*a33);
  a44=(a44+a36);
  a14=(a14*a34);
  a44=(a44-a14);
  a46=(a46+a44);
  a46=(a7*a46);
  a1=(a1+a46);
  a5=(a5-a1);
  if (res[0]!=0) res[0][10]=a5;
  a5=arg[0]? arg[0][11] : 0;
  a45=(a8*a45);
  a22=(a22+a45);
  a8=(a8*a23);
  a22=(a22+a8);
  a10=(a10*a11);
  a32=(a32*a33);
  a10=(a10+a32);
  a22=(a22+a10);
  a7=(a7*a22);
  a4=(a4+a7);
  a5=(a5-a4);
  if (res[0]!=0) res[0][11]=a5;
  return 0;
}

CASADI_SYMBOL_EXPORT int eql_ms(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int eql_ms_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int eql_ms_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eql_ms_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int eql_ms_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eql_ms_release(int mem) {
}

CASADI_SYMBOL_EXPORT void eql_ms_incref(void) {
}

CASADI_SYMBOL_EXPORT void eql_ms_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int eql_ms_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int eql_ms_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real eql_ms_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eql_ms_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eql_ms_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eql_ms_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eql_ms_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int eql_ms_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
